[package]
org = "ballerinai"
name = "transaction"
version = "@toml.version@"
distribution = "2201.10.0-20241019-091600-89e54c08"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
artifactId = "transaction"
version = "@project.version@"
path = "../transaction-native/build/libs/transaction-native-@project.version@.jar"
groupId = "ballerina"
