[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"
distribution = "2201.10.0-20241019-091600-89e54c08"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
artifactId = "transaction"
version = "1.10.1-SNAPSHOT"
path = "../transaction-native/build/libs/transaction-native-1.10.1-SNAPSHOT.jar"
groupId = "ballerina"
