[package]
org = "ballerinai"
name = "transaction_negative_tests"
version = "1.10.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../transaction-native/build/libs/transaction-native-1.10.1-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "transaction"
version = "1.10.1-SNAPSHOT"

[[platform.java21.dependency]]
path = "../transaction-test-utils/build/libs/transaction-test-utils-1.10.1-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.transaction"
scope = "testOnly"
artifactId = "transaction"
version = "1.10.1-SNAPSHOT"

[[platform.java21.dependency]]
path = "./lib/io-native-1.6.2-20240928-084100-656404f.jar"
groupId = "org.ballerinalang"
artifactId = "io-native"
version = "1.6.2-20240928-084100-656404f"
